server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${DB_URL}
    schemas: public
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
jobs:
  #  ex: 0 * * * * * (every minute)
  task-creation: ${TICKET_CREATION_JOB_PERIOD}